###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Delicia Gelada",
    "price": 5.50
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Pingado no ponto",
    "price": 3.00
}
